/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rainystar_intelligenthome_Communication */

#ifndef _Included_com_rainystar_intelligenthome_Communication
#define _Included_com_rainystar_intelligenthome_Communication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rainystar_intelligenthome_Communication
 * Method:    callQt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rainystar_intelligenthome_Communication_callQt__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rainystar_intelligenthome_Communication
 * Method:    callQt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rainystar_intelligenthome_Communication_callQt__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rainystar_intelligenthome_Communication
 * Method:    streamingVideo
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_rainystar_intelligenthome_Communication_streamingVideo
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
